### ISSUE TITLE
 Unhandled Exception: RangeError (index): Invalid value

### ISSUE THREAD

**Issue by ericel** [cngeru/georange#1]
> [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0

Seems to be working fine, except when no items within range distance.
It throws the above mentioned error

**Comment by cngeru** [comment]
This is not a `georange` issue. Check length of the array result returned after the fetch request takes place
