### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by torphix** [cngeru/georange#4]
Hello again,

I am attempting  to paginate my results using the query

   ```
 
```

The query works when not using start after document,

However app crashes and returns error message when:

**Comment by cngeru** [comment]
Can you share the full error message and accompanying functions

**Comment by henry8th** [comment]
Thanks for getting back to me,

The error occurs when using the function given in my first post.
The place an error occurs is when using .startAfterDocument(lastDoc)
just calling limit results in no error.



The error logs are as follows


An error occurred while parsing query arguments, this is most likely an error with this SDK. (
        0   CoreFoundation                      0x000000010fd38fba __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x000000010fbe2ff5 objc_exception_throw + 48
        2   FirebaseFirestore                   0x000000010a409caa _ZN8firebase9firestore4util16ObjcThrowHandlerENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 554
        3   FirebaseFirestore                   0x000000010a409135 _ZN8firebase9firestore4util5ThrowENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 53
        4   FirebaseFirestore                   0x000000010a6e0a85 _ZN8firebase9firestore4util20ThrowInvalidArgumentIJNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEES9_S9_EEEvPKcDpRKT_ + 85
        5   FirebaseFirestore                   0x000000010a6e06c7 _ZNK8firebase9firestore3api5Query20ValidateOrderByFieldERKNS0_5model9FieldPathES6_ + 119
        6   FirebaseFirestore                   0x000000010a6e0126 _ZNK8firebase9firestore3api5Que
Lost connection to device.

**Comment by cngeru** [comment]
Does running the query without the geohash give the samd error ?

**Comment by torphix** [comment]
No the error only occurs when using geohash filtering

**Comment by cngeru** [comment]
send the whole code snippet

**Comment by henry8th** [comment]
static Future<Map<dynamic, dynamic>> getServicesNearUser(
      {required String query,
      required int distance,
      DocumentSnapshot? lastDoc}) async {
    final geo = GeoRange();
    // Get current users long & lat
    final currentPoint = await LocationRepo.getCurrentPoint();
    // Get the geohash range of current user
    final Range geohashRange = geo.geohashRange(
        currentPoint.latitude, currentPoint.longitude,
        distance: distance);
    // Query based on users range first
    var buildingRef;
    var buildings;
    // First Query
    if (lastDoc == null) {
      buildingRef = await FirebaseFirestore.instance
          .collection('buildings')
          .where('$query')
          .where('$query.location.geohash',
              isGreaterThanOrEqualTo: geohashRange.lower)
          .where('$query.location.geohash',
              isLessThanOrEqualTo: geohashRange.upper)
          .limit(10)
          .get();
      // Paginate query
    } else {
      try {
        buildingRef = await FirebaseFirestore.instance
            .collection('buildings')
            .where('$query')
            .where('$query.location.geohash',
                isGreaterThanOrEqualTo: geohashRange.lower)
            .where('$query.location.geohash',
                isLessThanOrEqualTo: geohashRange.upper)
            .startAfterDocument(lastDoc)
            .limit(10)
            .get();
      } catch (e) {
        print(e);
      }
    }


Note: the try catch doesn't activate either, the app just crashes (on ios simulator)

**Comment by torphix** [comment]
Hi, hope all is well,  any progress? Are you able to replicate the issue?
Thank you kindly

**Comment by cngeru** [comment]
What's does this do `.where('$query')`

**Comment by torphix** [comment]
It returns without crashing.

Simulator only crashes when using

            .where('location.geohash',
                 isGreaterThanOrEqualTo: geohashRange.lower)
             .where('location.geohash',
                 isLessThanOrEqualTo: geohashRange.upper)

In conjunction with .startAtDocument()

**Comment by cngeru** [comment]
> What's does this do `.where('$query')`

in the original code base

and what's the new error message?

**Comment by henry8th** [comment]
Sorry I am confused as to what you want me to do?

I ran the same function with just .where('$query')
Where $query is equal to a variable name that I am passing in this case it is a persons first name

There is no error when running just .where($query)

The only time an error occurs is when .startAtDocument() is used is with

  .where('location.geohash',
             isGreaterThanOrEqualTo: geohashRange.lower)
         .where('location.geohash',
             isLessThanOrEqualTo: geohashRange.upper)

**Comment by henry8th** [comment]
Any updates?

**Comment by torphix** [comment]
For future people when performing query you must use .orderBy('geohash') before performing query

for completeness
```
        buildingRef = await FirebaseFirestore.instance
            .collection('buildings')
           .orderBy('geohash')
            .where('geohash',
                isGreaterThanOrEqualTo: geohashRange.lower)
            .where('geohash',
                isLessThanOrEqualTo: geohashRange.upper)
            .startAfterDocument(lastDoc)
            .limit(10)
            .get();

```
